### ISSUE TITLE
Warnings during build and in console

### ISSUE THREAD

**Issue by nmarra** [maximusk/extension-mechanism-demo#1]
Hi,

First off, incredible demo and great talk at NG Conf.  This has all been super helpful in trying to create the plugin / platform architecture I'm hoping to accomplish.  I was just wondering if you had a solution for the warnings I'm seeing when building your demo as they are tied directly to how you are importing and setting the SystemJS variable which seems to be one of the linchpins of getting this to work. 

WARNING in ./node_modules/@angular/core/esm5/core.js
6570:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/vendors.ts
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./src/vendors.ts

WARNING in ./node_modules/@angular/core/esm5/core.js
6590:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/vendors.ts
 @ multi (webpack)-dev-server/client?http://localhost:8081 ./src/vendors.ts

Thank you!

**Comment by maximusk** [comment]
Thanks! This warning is not related to SystemJS and doesn't affect runtime. 

It's produced by Webpack whenever it encounters an expression passed as a module name as in `require(someExpression)`. In the `/esm5/core.js` Angular contains the following code:
```
System.import(module)
```
where `module` is an expression and `System.import` is a Webpack's way to express dynamic require. However, it's used inside SystemJS loader inside Angular and it's not something Webpack should parse. It just happens to be an alias for `SystemJS.import()`. 

If it bothers you there's got to be a plugin that can be used to work around this warning.

**Comment by maximusk** [comment]
@nmarra , I don't think Angular v6 has any feature that will make the process easier. Maybe Ivy, but it will be released in v7 or v8. What exactly doesn't work in my setup with v6? Can you create a repo that I can take a look?

**Comment by nmarra** [comment]
Hi,

Yes I had realized that the v6 createElements process wasn't going to work
and I'd need to wait for Ivy to see if Angular was going to do anything to
solve this feature gap, so I put that work to the side and am using your
way of exporting and importing modules now.  I am currently running into an
issue importing an exported css file ( i.e. the extension module exports
the style.css file that compiles all the styles for the module instead of
inlining ) and am unable to get the styling to be used by the imported
extension module.  I've tried importing it in the platform's index file
like so without any luck:

<link rel="stylesheet" type="text/html"
href=="http://127.0.0.1:8081/dist/styles.css">


Any ideas would be appreciated :).  I'm trying to figure out how we
can make more complex modules and still export everything and import
it into a platform as you did with the simple module in your example.


Thank you,

-Nick Marra

**Comment by nmarra** [comment]
Max,

Sorry, this was a simple fix of just inlining the css with raw-loader in
webpack.  I apologize for bugging you about this stuff, I'm still getting
used to using webpack instead of the angular-cli.

-Nick Marra

**Comment by maximusk** [comment]
@nmarra , glad you solved it. No problem. Good luck!

**Comment by nmarra** [comment]
If anyone is interested to solve the console warnings the following can be added into the platforms' webpack.app.config's plugins section:

        `new ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)esm5/)`

And include the necessary require at the top:

`var ContextReplacementPlugin = require("webpack/lib/ContextReplacementPlugin");`

**Comment by nmarra** [comment]
Hi there again,

I've run into another issue using the extension mechanism and I was
wondering if you could take a look at it for me?  I've made a clone of your
repo and put a repo in my library up that demonstrates the issue:
https://github.com/nmarra/extension-angular-issue

I'm trying to just add some simple Angular code into the extension code ( a
simple *ngIf ), which requires me to import the CommonModule.  I've spent
the day trying multiple solutions to try and get around this but the
platform class constantly throws the below error:

ERROR Error: Uncaught (in promise): Error:
StaticInjectorError(AppModule)[NgIf -> ViewContainerRef]:
  StaticInjectorError(Platform: core)[NgIf -> ViewContainerRef]:
    NullInjectorError: No provider for ViewContainerRef!

If there is any way you could spend some time looking at this and explain
what I need to do to get it working I'd really appreciate it.  I'm trying
to build out a bigger extension example that has services and includes some
minified css ( like bootstrap ), but immediately ran into this roadblock
when trying to just use some simple Angular code.

Thank you for any help you can manage,
-Nick Marra
