### ISSUE TITLE
Troubles with modules in extension.

### ISSUE THREAD

**Issue by facundocoto** [maximusk/extension-mechanism-demo#2]
Hi, thanks for share the solution. I was found very useful. But, When I use modules (for example, HttpClient) in extension, when Compile and run it, the principal aplication throw a Exception 'No provider for Injector'. Do you have a idea what's could be?

**Comment by facundocoto** [comment]
To understand my trouble I'd created a repo with the code: https://github.com/facundocoto/extensionapp, 
To recreate the problem:
1. cd extern
1a. npm run build

2. cd ppal
2a. ng serve

The exception message is:
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[HttpHandler -> Injector]: 
  StaticInjectorError(Platform: core)[HttpHandler -> Injector]: 
    NullInjectorError: No provider for Injector!
Error: StaticInjectorError(AppModule)[HttpHandler -> Injector]: 
  StaticInjectorError(Platform: core)[HttpHandler -> Injector]: 
    NullInjectorError: No provider for Injector!
    at _NullInjector.get (core.js:1003)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveNgModuleDep (core.js:10896)
    at NgModuleRef_.get (core.js:12129)
    at resolveNgModuleDep (core.js:10896)
    at _NullInjector.get (core.js:1003)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveToken (core.js:1301)
    at tryResolveToken (core.js:1243)
    at StaticInjector.get (core.js:1111)
    at resolveNgModuleDep (core.js:10896)
    at NgModuleRef_.get (core.js:12129)
    at resolveNgModuleDep (core.js:10896)
    at resolvePromise (zone.js:814)
    at eval (zone.js:877)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4751)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)
defaultErrorLogger @ core.js:1449
ErrorHandler.handleError @ core.js:1510
next @ core.js:5508
schedulerFn @ core.js:4342
SafeSubscriber.__tryOrUnsub @ Subscriber.js:243
SafeSubscriber.next @ Subscriber.js:190
Subscriber._next @ Subscriber.js:131
Subscriber.next @ Subscriber.js:95
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4322
(anonymous) @ core.js:4782
ZoneDelegate.invoke @ zone.js:388
Zone.run @ zone.js:138
NgZone.runOutsideAngular @ core.js:4708
onHandleError @ core.js:4782
ZoneDelegate.handleError @ zone.js:392
Zone.runGuarded @ zone.js:154
_loop_1 @ zone.js:677
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
Promise.then (async)
scheduleMicroTask @ zone.js:578
ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
ZoneDelegate.scheduleTask @ zone.js:401
Zone.scheduleTask @ zone.js:232
Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
resolvePromise @ zone.js:808
(anonymous) @ zone.js:724
webpackJsonpCallback @ inline.bundle.js:22
(anonymous) @ externalapp.module.chunk.js:1

I think that could be for a bad implementation (mine) of dependencies, but I can't resolve.

Thanks

**Comment by maximusk** [comment]
@facundocoto is the error related to your own project or this project? If it's your own project, please create a question on stackoverflow and post a link here. I'll take a look

**Comment by facundocoto** [comment]
@maximusk thanks for answering. Yes, is my own proyect... I created the answer in stackoverflow, the link is:  https://stackoverflow.com/questions/50412904/import-extern-module-in-running-app-with-angular-5
If you can please take a look. 
Thanks! Facundo.

**Comment by nmarra** [comment]
@facundocoto did you ever find a solution to this issue?  I'm not seeing anything on your stackoverflow and this seems somewhat related to my issue https://github.com/maximusk/extension-mechanism-demo/issues/4 and this issue https://github.com/maximusk/extension-mechanism-demo/issues/3 .  I'm very interested in how this can be solved.

**Comment by facundocoto** [comment]
Hi @nmarra. Yes, wue could say, but not with Max's solution (He helped me solve it). So as not to disturb him, write me to my email (facundocoto1@gmail.com) and we'll talk. Greetings
