### ISSUE TITLE
Load extension that uses third party module (primeNg)

### ISSUE THREAD

**Issue by SaifJerbi** [maximusk/extension-mechanism-demo#3]
Hi @maximusk,

I appreciate your solution but there are some limitations: 
I forked your project, i run it => it works well
But if i add any third party module to the "extension module", the loader fail when trying to create the component.
In my case, i added primeng library and i used the primeng button in my extension component template. 
When i try to import the extension, i got this error:

`ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[NgClass -> IterableDiffers]: 
  StaticInjectorError(Platform: core)[NgClass -> IterableDiffers]: 
    NullInjectorError: No provider for IterableDiffers!
Error: StaticInjectorError(AppModule)[NgClass -> IterableDiffers]: 
  StaticInjectorError(Platform: core)[NgClass -> IterableDiffers]: 
    NullInjectorError: No provider for IterableDiffers!
    at _NullInjector.get (app.bundle.js:3153)`

I'm developing a modular web IDE using angular and nodeJs. I have to provide an extension loading mechanism in order to allow users to plug only plugins that they need.
The extension in my case are some rich angular screens

**Comment by stefanocke** [comment]
Hi @SaifJerbi,  I have a workin example with primeng button. Please see https://github.com/maximusk/extension-mechanism-demo/issues/4#issuecomment-417943385

**Comment by SaifJerbi** [comment]
Hi @stefanocke , Thanks for your response.
I have implemented the same solution and it works well.
But there are a limitation: Each third party library that is used in your extension must be loaded and provided in the core platform:
``` typescript
import * as prime from 'primeng/primeng';
import * as lodash from 'lodash';

SystemJS.set('primeng/primeng', SystemJS.newModule(prime));
SystemJS.set('lodash', SystemJS.newModule(lodash));

```
So i'm trying to find a way to load this third party libraries at runtime also, and implement a mechanism that allow developers to declare what they are using in there extension and provide the required files to be served at runtime.
Or there are also another solution is to bundle the third party libraries embeded with the extension bundle

**Comment by stefanocke** [comment]
@SaifJerbi, of course there is a bunch of ways you can go now, depending on your exact requirements. But maybe this issue is not the right place to discuss this futher. Your original problem is solved, isn't it?

**Comment by SaifJerbi** [comment]
Hi @stefanocke, Yeah the problem is resolved.
If you have any proposal, can you join me by email?  (m.jerbi.saif@gmail.com)
